apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Changes port to 110"
  name: deployment-test
  labels:
    app: front
spec:
  revisionHistoryLimit: 1
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/change-cause: "Primer creación del servicio"
  name: my-service
  labels:
    app: front
spec:
  selector:
    app.kubernetes.io/name: front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80